### ISSUE TITLE
Lista de usuarios del sistema

### ISSUE THREAD

**Issue by Alek7Villa** [AgoraUS-G1-1617/Autenticacion_b#11]
Hola, tenemos una pequeña duda sobre vuestra API, quisiéramos saber cómo podríamos consultar la lista de usuario al utilizar vuestra API.
Saludos.

**Comment by alerodrom** [comment]
Buenas! Para hacer consultas a nuestra API se deberá usar de la siguiente manera:  http://authb.agoraus1.egc.duckdns.org/api/index.php?method=nombreMetodo&param=value
