### ISSUE TITLE
Error en los enlaces una vez logueado

### ISSUE THREAD

**Issue by PabloMorle** [AgoraUS-G1-1617/Autenticacion_b#12]
Buenas.

Cuando logueo con un usuario cualquiera y luego intento acceder a cualquier otro subsistema a traves de los enlaces proporcionados (https://beta.authb.agoraus1.egc.duckdns.org/welcome.php) me redirige a localhost:90, haciendo imposible la navegación.

Saludos.

**Comment by carruivar** [comment]
Se han modificado los enlaces de acceso al resto de subsistemas.
