### ISSUE TITLE
API Mal configurada.

### ISSUE THREAD

**Issue by ismdepue** [AgoraUS-G1-1617/Autenticacion_b#18]
El objeto
**
    * \brief Comprobar usuario
    * \details Comprobar si un usuario dado está ya autenticado en el sistema,
    * comprobando un token.
    * \return JSON
    */
    function checkTokenUser($token, $user) {

No devuelve el usuario autenticado en el sistema, devuelve si un usuario está registrado o no.

**Comment by alerodrom** [comment]
Ya esta cambiada la descripción del método gracias!
