### ISSUE TITLE
Fallo al registrarte con Facebook

### ISSUE THREAD

**Issue by manucc07** [AgoraUS-G1-1617/Autenticacion_b#21]
al intentar registrarme con Facebook https://authb.agoraus1.egc.duckdns.org/loginFacebook.php

![429701578_36073_4616613950281906773](https://cloud.githubusercontent.com/assets/23355524/21779721/1ec805ba-d6a9-11e6-901d-b80bbbf05d8d.jpg)

**Comment by alerodrom** [comment]
Ya esta solucionado, hemos creado una nueva aplicación para la rama máster
