### ISSUE TITLE
El registro con Facebook no funciona en https://beta.authb.agoraus1.egc.duckdns.org/

### ISSUE THREAD

**Issue by Rubsuaalm** [AgoraUS-G1-1617/Autenticacion_b#27]
Debería de funcionar tanto en:
https://beta.authb.agoraus1.egc.duckdns.org/
https://authb.agoraus1.egc.duckdns.org/

**Comment by alerodrom** [comment]
Buenas @Rubsuaalm ya esta solucionada!
