### ISSUE TITLE
Login no funciona

### ISSUE THREAD

**Issue by Dionakra** [AgoraUS-G1-1617/Autenticacion_b#3]
Buenas.

He realizado un login con el usuario **pabcargar2**, "obteniendo" su contraseña en la página sin DNIe (https://beta.authb.agoraus1.egc.duckdns.org/loginNotDNIe.php) y, en logins exitosos, envía a una página que no existe y devuelve "File Not Found". En concreto redirige a https://beta.authb.agoraus1.egc.duckdns.org/agoraus.freeoda.com/welcome.php

Saludos.

**Comment by alerodrom** [comment]
El login ya funciona correctamente en la versión beta de nuestra aplicación @Dionakra
