### ISSUE TITLE
No es posible acceder a la cookie de user o token

### ISSUE THREAD

**Issue by josjimjim** [AgoraUS-G1-1617/Autenticacion_b#31]
No es posible acceder a la cookie de user o token desde fuera del dominio de autenticación, y necesitamos ambas para poder validar tanto al usuario que realiza los votos como para asegurarnos de que se encuentra logueado.

Como posible solución, @agubelu nos recomienda que se especifique el dominio completo de agora-us de la siguiente forma, para poder acceder desde cualquier subdominio, quedando por ejemplo para el de token:

`setcookie("token_usuario", $token, 0, "/", "agoraus1.egc.duckdns.org");`

**Comment by alerodrom** [comment]
Hemos aplicado un cambio en cuanto puedas comprueba si funciona correctamente @raisans138.

**Comment by agubelu** [comment]
Creo que no lo habéis puesto bien, el dominio va en el quinto parámetro de la función (el que seguís teniendo como ""), además hay una coma de más por lo que da error de sintaxis (la página no funciona y vuestra build de Travis falla).

**Comment by alerodrom** [comment]
Ya esta solucionado! Gracias @agubelu @raisans138
